"""Runtime boundaries for local execution, storage, and compatibility-aware paths."""

from .catalog import (
    SOURCE_PRIORITIES,
    canonical_job_content_hash,
    canonical_job_dedupe_key,
    canonical_job_row,
    ingest_catalog_job,
    job_needs_enrichment,
    job_source_record_row,
    load_source_record_index,
    merge_canonical_job_row,
    source_job_key,
    source_platform,
    source_priority,
    source_record_id,
)
from .jobsync import record_jobsync_application_status_event
from .reactive_resume import record_reactive_resume_document_ref
from .paths import (
    application_state_path,
    artifacts_root,
    data_root,
    db_root,
    documents_root,
    exports_root,
    gmail_credentials_path,
    gmail_token_path,
    jobs_delta_path,
    jobs_expired_path,
    jobs_state_path,
    primary_db_path,
    profile_embedding_cache_path,
    profile_pack_path,
    repo_root,
    resume_json_path,
    suggested_jobs_path,
)

__all__ = [
    "SOURCE_PRIORITIES",
    "application_state_path",
    "artifacts_root",
    "canonical_job_content_hash",
    "canonical_job_dedupe_key",
    "canonical_job_row",
    "data_root",
    "db_root",
    "documents_root",
    "exports_root",
    "gmail_credentials_path",
    "gmail_token_path",
    "ingest_catalog_job",
    "job_needs_enrichment",
    "job_source_record_row",
    "jobs_delta_path",
    "jobs_expired_path",
    "jobs_state_path",
    "load_source_record_index",
    "merge_canonical_job_row",
    "primary_db_path",
    "profile_embedding_cache_path",
    "profile_pack_path",
    "record_jobsync_application_status_event",
    "record_reactive_resume_document_ref",
    "repo_root",
    "resume_json_path",
    "source_job_key",
    "source_platform",
    "source_priority",
    "source_record_id",
    "suggested_jobs_path",
]
